### ISSUE TITLE
Home Assistant 2020.12.0 Illuminance sensors not working anymore

### ISSUE THREAD

**Issue by benleb** [benleb/ad-automoli#58]
The last commits seem to have fixed the canceling but it only worked until I updated to `Home Assistant 2020.12.0` now the lights show as turned on in home assistant but in reality they dim down and won't turn back on ever as home assistant sees them as on. Not sure if this is a HA bug or an issue here.

_Originally posted by @paviro in https://github.com/benleb/ad-automoli/issues/10#issuecomment-745389089_

**Comment by benleb** [comment]
See #10 for reference... repost of my last comment:

Ok so we have problems since 2020.12...

Humidity Sensor is ignored
Lights show as on but they aren’t (see below)
Anything else? If you have other info which could be useable, tell me ;) I will try to reproduce this and find the bug over the weekend ✌️

As automoli does not change the state directly, just via the home assistant services, I expect that if lights have a wrong state in home assistant, it must be something else... But will investigate this too!

**Comment by paviro** [comment]
Not sure if my issue is related to dimming or just a zigbee issue in 2020.12.0. I am using scenes, some have individual lights (in the evening for example) and some use a zigbee group to combine all during day. 

They all dim down, only in home assistant sometimes one of the lights is till on = the whole group is shown as on, the reason automoli won't turn it back on if the current scene uses the zigbee group light which is shown as still on.

**Comment by paviro** [comment]
Some further notes: The issue only seems to happen when a motion sensor gets triggered while the lights dimm down.

This is the lights in their on state:
<img width="389" alt="sdfsdfkjsdf" src="https://user-images.githubusercontent.com/992826/102829606-c49c0e00-43e7-11eb-8c09-6a069be20b49.png">

If I let them dim down completely and only then move again everything works fine. If I move before they are dimmed down to cancel the dimming some lights get "stuck":
<img width="393" alt="jsdflsjfdl" src="https://user-images.githubusercontent.com/992826/102829665-e85f5400-43e7-11eb-8345-bb775a3d8489.png">

Not sure why maybe some detail in the zigbee implementation. It seems like HASS sends the transition state to the zigbee network but not the new on state somehow. Any way I can help you debug this?

**Comment by thundergreen** [comment]
I face another problem. My lights turn on even if the illuminance_threshold: 25 is excedded.

this is my config:

```
dressing:
  module: automoli
  class: AutoMoLi
  room: Dressing
  disable_switch_entities:
    - input_boolean.automoli_general
    - group.persons
  disable_switch_states:
    - "off"
    - not_home
  delay: 10
  daytimes:
    - { starttime: "05:30", name: morning, light: 1 }
    - { starttime: "07:30", name: day, light: 10 }
    - { starttime: "20:30", name: evening, light: 5 }
    - { starttime: "22:30", name: night, light: 1 }
    - { starttime: "23:30", name: more_night, light: 1 }
  illuminance_threshold: 20
  illuminance:
    - sensor.average_luminance_in_the_house
  lights:
    - light.dressing
  motion:
    - binary_sensor.multisensor_dressing_motion
  motion_state_on: "on"
  motion_state_off: "off"
```
and the light sensor value of ```sensor.average_luminance_in_the_house``` is: ```23.25´´´

any idea what`s going n here?

**Comment by benleb** [comment]
hey, please  try https://github.com/benleb/ad-automoli/releases/tag/v0.9.0b1 

and... this all just occurred with dimming activated right? I think the problem was my fault and introduced with the dimming :(

**Comment by paviro** [comment]
Is bis supposed to fix both or only the luminance related bug?

**Comment by benleb** [comment]
just the illuminance/humidity thing and a little how the dimming works... you are referring to the zha issue right? maybe that's solved by the modification to the dimming logic. if not... afaik it could be helpful if automoli would set the state of the lights explicitly after switching on/off/dimming? that would be possible to do

**Comment by paviro** [comment]
That would probably solve the issue for now until home assistant itself has the behavior of assuming it worked until it gets a different state back from the network.

**Comment by paviro** [comment]
The new updates don't help with the ZHA issues unfortunately.

**Comment by benleb** [comment]
Hey @paviro okay... I added a piece of code to set the states explicitly to off when dimming starts (= should be switched on, on motion) in https://github.com/benleb/ad-automoli/commit/cd15873fc47c6b7e51d66de0fdb18a822ca14ec4

Does this work for you?

**Comment by paviro** [comment]
It seems like when the lights are dimmed down the state in home assistant is now correctly reflected and they indeed turn off but I still can't cancel the dimming:

```
2020-12-30 16:25:04.460744 INFO schlafzimmer_bewegungsmelder: 💡 Schlafzimmer turned on → ha scene: schlafzimmer_abend | delay: 10sec
2020-12-30 16:25:17.604827 INFO schlafzimmer_bewegungsmelder:  motion_cleared(..) binary_sensor.schlafzimmer_treppe_bewegung changed state from on to off
2020-12-30 16:25:17.616724 INFO schlafzimmer_bewegungsmelder:  clear_handles(..) self.handles = set() cleared, canceling handles = set()
2020-12-30 16:25:24.227936 INFO schlafzimmer_bewegungsmelder:  motion_cleared(..) binary_sensor.schlafzimmer_schreibtisch_bewegung changed state from on to off
2020-12-30 16:25:24.242482 INFO schlafzimmer_bewegungsmelder:  clear_handles(..) self.handles = set() cleared, canceling handles = set()
2020-12-30 16:25:24.248136 INFO schlafzimmer_bewegungsmelder:  refresh_timer(..) handles cleared → self.handles = set()
2020-12-30 16:25:24.253800 INFO schlafzimmer_bewegungsmelder:  refresh_timer(..) self.active = {'daytime': 'abend', 'delay': 10, 'starttime': '16:05:22', 'light_setting': 'scene.schlafzimmer_abend', 'is_hue_group': False}
2020-12-30 16:25:24.258941 INFO schlafzimmer_bewegungsmelder:  refresh_timer(..) self.dim = {'brightness_step_pct': None, 'seconds_before': 10, 'method': 1}, dimming in 0
2020-12-30 16:25:24.267924 INFO schlafzimmer_bewegungsmelder:  refresh_timer(..) dim_handle = 'c78925517a124c9799a919f3090d5b52' -> {'c78925517a124c9799a919f3090d5b52'}
2020-12-30 16:25:24.282524 INFO schlafzimmer_bewegungsmelder:  refresh_timer(..) off_handle = '3aa656d7e2274679abda5b031a6a73d7' -> {'c78925517a124c9799a919f3090d5b52', '3aa656d7e2274679abda5b031a6a73d7'}
2020-12-30 16:25:24.293064 INFO schlafzimmer_bewegungsmelder:  self.thresholds.get('humidity') = None
2020-12-30 16:25:24.297901 INFO schlafzimmer_bewegungsmelder:  dim_lights(..) await self.is_disabled() = False | await self.is_blocked() = False
2020-12-30 16:25:24.310181 INFO schlafzimmer_bewegungsmelder:  self.thresholds.get('humidity') = None
2020-12-30 16:25:24.318167 INFO schlafzimmer_bewegungsmelder:  dim_lights(..) dim_method = <DimMethod.TRANSITION: 1> - seconds_before = 10
2020-12-30 16:25:24.323070 INFO schlafzimmer_bewegungsmelder:  dim_lights(..) dim_attributes = {'transition': 10}
2020-12-30 16:25:25.331182 INFO schlafzimmer_bewegungsmelder: 🌑 Schlafzimmer → transition to off (10sec)
2020-12-30 16:25:28.046680 INFO schlafzimmer_bewegungsmelder:  motion detected(..) binary_sensor.schlafzimmer_schreibtisch_bewegung changed state from off to on
2020-12-30 16:25:28.052752 INFO schlafzimmer_bewegungsmelder:  clear_handles(..) self.handles = set() cleared, canceling handles = {'c78925517a124c9799a919f3090d5b52', '3aa656d7e2274679abda5b031a6a73d7'}
2020-12-30 16:25:28.066033 INFO schlafzimmer_bewegungsmelder:  motion_detected(..) handles cleared and cancelled all scheduled timers
2020-12-30 16:25:28.071843 INFO schlafzimmer_bewegungsmelder:  motion_event(..) received 'state_changed_detection' event from 'binary_sensor.schlafzimmer_schreibtisch_bewegung'
2020-12-30 16:25:28.078423 INFO schlafzimmer_bewegungsmelder:  motion_event(..) await self.is_disabled() = False
2020-12-30 16:25:28.086813 INFO schlafzimmer_bewegungsmelder:  motion_event(..) light in Schlafzimmer already on → refreshing the timer
```
See `motion_event(..) light in Schlafzimmer already on → refreshing the timer`

**Comment by benleb** [comment]
okay, thanks for the logs! I have another idea to workaround. But no problem if you are not willing to test anymore 😅

**Comment by paviro** [comment]
Totally willing! :D You are trying to fix my issue after all :D

**Comment by benleb** [comment]
ok, pushed a new variant with an explicit "dimming" state... its a dirty hack for now, but works - at least for me 😅

![image](https://user-images.githubusercontent.com/512997/103371612-2fc49f00-4ad0-11eb-9e38-d6e693a3d7b8.png)

**Comment by paviro** [comment]
It works!!! Thank you! :D ❤️

**Comment by thundergreen** [comment]
My illuminance issue persists. Input_boolean is taken into consideration but sensors states not. My only workaround would be dirt ugly by creating automatios which toggle input_booleans :(  I ried Docker install and same issue @benleb

**Comment by ChrisHaPunkt** [comment]
Facing the same humidity/illuminance issue over here

**Comment by thundergreen** [comment]
Happy that I'm not the only one 😂

**Comment by sivastola** [comment]
I'm having the same issue with illumination. Maybe it helps, or not, I will document what I have and get in the log files.

1. configuration file:
`motion_dachboden:
  module: automoli
  class: AutoMoLi
  room: Dachboden
  delay: 60
  daytimes:
    - { starttime: "08:00", name: day, light: 100 }
    - { starttime: "18:30", name: night, light: 100 }
  illuminance: sensor.000d5a49919777_average_illumination
  illuminance_threshold: 30
  lights:
    - light.dachboden
  motion:
    - binary_sensor.presence_10
    - binary_sensor.presence_20
  motion_state_on: "on"
  motion_state_off: "off"
`

2. Logfile when motion-part is changed:
`2021-01-08 10:21:32.724272 INFO motion_dachboden:  
2021-01-08 10:21:32.725946 INFO motion_dachboden: 💡 AutoMoLi v0.9.1 · Dachboden
2021-01-08 10:21:32.727323 INFO motion_dachboden:  
2021-01-08 10:21:32.728823 INFO motion_dachboden:    illuminance: sensor.000d5a49919777_average_illumination
2021-01-08 10:21:32.730263 INFO motion_dachboden:    room: Dachboden
2021-01-08 10:21:32.731803 INFO motion_dachboden:    delay: 1:00min ≈ 60sec
2021-01-08 10:21:32.733205 INFO motion_dachboden:    active_daytime: day
2021-01-08 10:21:32.734626 INFO motion_dachboden:    daytimes:
2021-01-08 10:21:32.736088 INFO motion_dachboden:      day:
2021-01-08 10:21:32.737782 INFO motion_dachboden:        starttime: 08:00
2021-01-08 10:21:32.739461 INFO motion_dachboden:        light: 100
2021-01-08 10:21:32.740953 INFO motion_dachboden:      night:  
2021-01-08 10:21:32.742490 INFO motion_dachboden:        starttime: 18:30
2021-01-08 10:21:32.744085 INFO motion_dachboden:        light: 100
2021-01-08 10:21:32.745446 INFO motion_dachboden:    lights:
2021-01-08 10:21:32.746879 INFO motion_dachboden:      · light.dachboden
2021-01-08 10:21:32.748317 INFO motion_dachboden:    dim:
2021-01-08 10:21:32.749817 INFO motion_dachboden:    threshold:
2021-01-08 10:21:32.751251 INFO motion_dachboden:      illuminance: 30
2021-01-08 10:21:32.752654 INFO motion_dachboden:    sensors:
2021-01-08 10:21:32.754123 INFO motion_dachboden:      motion:
2021-01-08 10:21:32.755567 INFO motion_dachboden:        · binary_sensor.presence_10
2021-01-08 10:21:32.757091 INFO motion_dachboden:        · binary_sensor.presence_20
2021-01-08 10:21:32.760442 INFO motion_dachboden:      illuminance: []
2021-01-08 10:21:32.761884 INFO motion_dachboden:    disable_hue_groups: False
2021-01-08 10:21:32.763298 INFO motion_dachboden:    only_own_events: False
2021-01-08 10:21:32.764781 INFO motion_dachboden:    loglevel: 20
2021-01-08 10:21:32.766193 INFO motion_dachboden:  
`

3. Logfile when motion was detected:
`2021-01-08 02:28:43.159143 INFO motion_dachboden: 💡 Dachboden turned on → brightness: 100% | delay: 1min
2021-01-08 02:30:43.025171 INFO motion_dachboden: 🌑 no motion in Dachboden since 1min → turned off
`

As far as I remember when motion was detected I saw some calculation in the log, like
current illuminance is XX and threshold is YY so light will switch on or not.

regards

**Comment by sivastola** [comment]
I'm having the same issue with illumination. Maybe it helps, or not, I will document what I have and get in the log files.

1. configuration file:
```
motion_dachboden:
  module: automoli
  class: AutoMoLi
  room: Dachboden
  delay: 60
  daytimes:
    - { starttime: "08:00", name: day, light: 100 }
    - { starttime: "18:30", name: night, light: 100 }
  illuminance: sensor.000d5a49919777_average_illumination
  illuminance_threshold: 30
  lights:
    - light.dachboden
  motion:
    - binary_sensor.presence_10
    - binary_sensor.presence_20
  motion_state_on: "on"
  motion_state_off: "off"
```

2. Logfile when motion-part is changed:
```
2021-01-08 10:21:32.724272 INFO motion_dachboden:  
2021-01-08 10:21:32.725946 INFO motion_dachboden: 💡 AutoMoLi v0.9.1 · Dachboden
2021-01-08 10:21:32.727323 INFO motion_dachboden:  
2021-01-08 10:21:32.728823 INFO motion_dachboden:    illuminance: sensor.000d5a49919777_average_illumination
2021-01-08 10:21:32.730263 INFO motion_dachboden:    room: Dachboden
2021-01-08 10:21:32.731803 INFO motion_dachboden:    delay: 1:00min ≈ 60sec
2021-01-08 10:21:32.733205 INFO motion_dachboden:    active_daytime: day
2021-01-08 10:21:32.734626 INFO motion_dachboden:    daytimes:
2021-01-08 10:21:32.736088 INFO motion_dachboden:      day:
2021-01-08 10:21:32.737782 INFO motion_dachboden:        starttime: 08:00
2021-01-08 10:21:32.739461 INFO motion_dachboden:        light: 100
2021-01-08 10:21:32.740953 INFO motion_dachboden:      night:  
2021-01-08 10:21:32.742490 INFO motion_dachboden:        starttime: 18:30
2021-01-08 10:21:32.744085 INFO motion_dachboden:        light: 100
2021-01-08 10:21:32.745446 INFO motion_dachboden:    lights:
2021-01-08 10:21:32.746879 INFO motion_dachboden:      · light.dachboden
2021-01-08 10:21:32.748317 INFO motion_dachboden:    dim:
2021-01-08 10:21:32.749817 INFO motion_dachboden:    threshold:
2021-01-08 10:21:32.751251 INFO motion_dachboden:      illuminance: 30
2021-01-08 10:21:32.752654 INFO motion_dachboden:    sensors:
2021-01-08 10:21:32.754123 INFO motion_dachboden:      motion:
2021-01-08 10:21:32.755567 INFO motion_dachboden:        · binary_sensor.presence_10
2021-01-08 10:21:32.757091 INFO motion_dachboden:        · binary_sensor.presence_20
2021-01-08 10:21:32.760442 INFO motion_dachboden:      illuminance: []
2021-01-08 10:21:32.761884 INFO motion_dachboden:    disable_hue_groups: False
2021-01-08 10:21:32.763298 INFO motion_dachboden:    only_own_events: False
2021-01-08 10:21:32.764781 INFO motion_dachboden:    loglevel: 20
2021-01-08 10:21:32.766193 INFO motion_dachboden:  
```

3. Logfile when motion was detected:
```
2021-01-08 02:28:43.159143 INFO motion_dachboden: 💡 Dachboden turned on → brightness: 100% | delay: 1min
2021-01-08 02:30:43.025171 INFO motion_dachboden: 🌑 no motion in Dachboden since 1min → turned off
```

As far as I remember when motion was detected I saw some calculation in the log, like
current illuminance is XX and threshold is YY so light will switch on.

regards

**Comment by thundergreen** [comment]
Another Problem ... I have my kitchen automation like this:

```
kitchen:
  module: automoli
  class: AutoMoLi
  room: Kitchen
  disable_switch_entities:
    - input_boolean.automoli_general
  delay: 260
  daytimes:
    - { starttime: "05:30", name: morning, light: 1 }
    - { starttime: "06:45", name: day, light: 20 }
    - { starttime: "08:00", name: day, light: 50 }
    - { starttime: "10:00", name: day, light: 100 }
    - { starttime: "17:30", name: more_day, light: 100 }
    - { starttime: "20:30", name: evening, light: 100 }
    - { starttime: "21:30", name: night, light: 30 }
    - { starttime: "22:30", name: more_night, light: 0 }
  illuminance_threshold: 20
  illuminance:
    - sensor.average_luminance_in_the_house
  motion:
    - binary_sensor.motion_sensor_158d0001549b4b
  motion_state_on: "on"
  motion_state_off: "off"
  lights:
    - light.kitchen
  dim:
    method: transition
    seconds_before: 15

```

Somehow the light will turn off even if there was motion in between :(

**Comment by benleb** [comment]
sorry, working on a fix ✌️

**Comment by benleb** [comment]
> Another Problem ... I have my kitchen automation like this:
> 
> 
> 
> ```
> 
> kitchen:
> 
>   module: automoli
> 
>   class: AutoMoLi
> 
>   room: Kitchen
> 
>   disable_switch_entities:
> 
>     - input_boolean.automoli_general
> 
>   delay: 260
> 
>   daytimes:
> 
>     - { starttime: "05:30", name: morning, light: 1 }
> 
>     - { starttime: "06:45", name: day, light: 20 }
> 
>     - { starttime: "08:00", name: day, light: 50 }
> 
>     - { starttime: "10:00", name: day, light: 100 }
> 
>     - { starttime: "17:30", name: more_day, light: 100 }
> 
>     - { starttime: "20:30", name: evening, light: 100 }
> 
>     - { starttime: "21:30", name: night, light: 30 }
> 
>     - { starttime: "22:30", name: more_night, light: 0 }
> 
>   illuminance_threshold: 20
> 
>   illuminance:
> 
>     - sensor.average_luminance_in_the_house
> 
>   motion:
> 
>     - binary_sensor.motion_sensor_158d0001549b4b
> 
>   motion_state_on: "on"
> 
>   motion_state_off: "off"
> 
>   lights:
> 
>     - light.kitchen
> 
>   dim:
> 
>     method: transition
> 
>     seconds_before: 15
> 
> 
> 
> ```
> 
> 
> 
> Somehow the light will turn off even if there was motion in between :( 
> 
> 

please use another issue for this, let's focus on illuminance here 👍

**Comment by ChrisHaPunkt** [comment]
Just a hint because it's all about illuminance in the tiltle. The humidity functionality is still not working as well for my setup, cannot tell if it's related. I created automations to trigger an input_boolean for this cases as a workaround.

**Comment by thundergreen** [comment]
any news here? I will also open another issue where the autoomoli will kick in even if the controlling lamp is already turned ON

**Comment by benleb** [comment]
try this please, I think I got it :P

**Comment by sivastola** [comment]
It works.
Checked illumance only, not using humidity.

Thank you.

**Comment by benleb** [comment]
ok, there you go 💁‍♀️ https://github.com/benleb/ad-automoli/releases/tag/v0.10.0
